### ISSUE TITLE
README instructions doesn't work

### ISSUE THREAD

**Issue by nicolasmery** [jasonish/docker-suricata-elk#1]
Hi, I followed the Readme's instructions and I was unable to run your app. 

I run "./launcher start -i eth0" 

And when using the latest docker image this error appears:

```
/tools/boot: line 6: /config: No such file or directory
```

The same happens after building myself the image.

Maybe there is a configuration file that I'm not mounting?

Also I thought that maybe the lastest image had a bug so I tried the one tagged as master and seems to work fine at first but then this error appears:

```
INFO spawnerr: can't find command '/opt/elasticsearch/bin/elasticsearch'
```

**Comment by jasonish** [comment]
Will look at this right away.  Its because I modified the base image (which
is a more plain Suricata image) in an incompatible way with this image -
oops.

**Comment by jasonish** [comment]
Should be fixed.  git pull, make build, restart...
